### ISSUE TITLE
modprobe: page allocation failure

### ISSUE THREAD

**Issue by John2k12** [bootc/linux#2]
After kernel compilation i get his message while booting up:

EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
vmalloc: allocation failure: 0 bytes
modprobe: page allocation failure: order:0, mode:0xd0
Backtrace:
Function entered at [<c0011738>] from [<c03019b8>]
 r6:c032f1c4 r5:000000d0 r4:00000001 r3:c03a71c8
Function entered at [<c03019a0>] from [<c00558f4>]
Function entered at [<c005582c>] from [<c0073a44>]
 r3:00000000 r2:c032f1c4
 r8:000000d0 r7:ffffffff r6:c00499e8 r5:000003e8 r4:00000000
Function entered at [<c00738b8>] from [<c00122e0>]
 r8:ce903028 r7:c0307e78 r6:00000000 r5:000003e8 r4:000000d0
Function entered at [<c00122a4>] from [<c00499e8>]
 r4:bf081000
Function entered at [<c00499d4>] from [<c004a2d8>]
 r6:00000019 r5:000003e8 r4:bf081000 r3:00000000
Function entered at [<c0049a60>] from [<c000dfc0>]
Mem-info:
Normal per-cpu:
CPU    0: hi:   90, btch:  15 usd:  38
active_anon:438 inactive_anon:30 isolated_anon:0
 active_file:1295 inactive_file:1934 isolated_file:0
 unevictable:405 dirty:0 writeback:0 unstable:0
 free:50315 slab_reclaimable:305 slab_unreclaimable:635
 mapped:472 shmem:32 pagetables:78 bounce:0
Normal free:201260kB min:1908kB low:2384kB high:2860kB active_anon:1752kB inactive_anon:120kB active_file:5180kB inactive_file:7736kB unevictable:1620kB isolated(anon):0kB isolated(file):0kB present:227584kB mlocked:1620kB dirty:0kB writeback:0kB mapped:1888kB shmem:128kB slab_reclaimable:1220kB slab_unreclaimable:2540kB kernel_stack:360kB pagetables:312kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
lowmem_reserve[]: 0 0
Normal: 177_4kB 169_8kB 106_16kB 52_32kB 22_64kB 3_128kB 4_256kB 1_512kB 2_1024kB 1_2048kB 46*4096kB = 201260kB
3595 total pagecache pages
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
57344 pages of RAM
50449 free pages
1519 reserved pages
940 slab pages
3254 pages shared
0 pages swap cached
### snd_bcm2835_alsa_probe c03a6218 ############### PROBING FOR bcm2835 ALSA device (0):(1)

RPi seems to work normally, but it would be nice to know what causes this failure.

Thx and best regards,

John

**Comment by John2k12** [comment]
I've enabled kobject debugging, maybe its helpfull:

kobject: 'snd_page_alloc' (bf06e98c): kobject_uevent_env
kobject: 'snd_page_alloc' (bf06e98c): fill_kobj_path: path = '/module/snd_page_alloc'
kobject: 'snd_pcm' (bf07dd20): kobject_add_internal: parent: 'module', set: 'module'
kobject: 'holders' (cc8a38e0): kobject_add_internal: parent: 'snd_pcm', set: '<NULL>'
kobject: 'snd_pcm' (bf07dd20): kobject_uevent_env
kobject: 'snd_pcm' (bf07dd20): fill_kobj_path: path = '/module/snd_pcm'
vmalloc: allocation failure: 0 bytes
modprobe: page allocation failure: order:0, mode:0xd0
Backtrace:
Function entered at [<c0011738>] from [<c0301bd4>]
 r6:c032f224 r5:000000d0 r4:00000001 r3:c03a71c8
Function entered at [<c0301bbc>] from [<c00558f4>]
Function entered at [<c005582c>] from [<c0073a44>]
 r3:00000000 r2:c032f224
 r8:000000d0 r7:ffffffff r6:c00499e8 r5:000003e8 r4:00000000
Function entered at [<c00738b8>] from [<c00122e0>]
 r8:ce903028 r7:c0307e78 r6:00000000 r5:000003e8 r4:000000d0
Function entered at [<c00122a4>] from [<c00499e8>]
 r4:bf081000
Function entered at [<c00499d4>] from [<c004a2d8>]
 r6:00000019 r5:000003e8 r4:bf081000 r3:00000000
Function entered at [<c0049a60>] from [<c000dfc0>]
Mem-info:
Normal per-cpu:
CPU    0: hi:   90, btch:  15 usd:  30
active_anon:430 inactive_anon:30 isolated_anon:0
 active_file:1046 inactive_file:2344 isolated_file:0
 unevictable:405 dirty:0 writeback:0 unstable:0
 free:50197 slab_reclaimable:302 slab_unreclaimable:610
 mapped:473 shmem:32 pagetables:79 bounce:0
Normal free:200788kB min:1908kB low:2384kB high:2860kB active_anon:1720kB inactive_anon:120kB active_file:4184kB inactive_file:9376kB unevictable:1620kB isolated(anon):0kB isolated(file):0kB present:227584kB mlocked:1620kB dirty:0kB writeback:0kB mapped:1892kB shmem:128kB slab_reclaimable:1208kB slab_unreclaimable:2440kB kernel_stack:360kB pagetables:316kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
lowmem_reserve[]: 0 0
Normal: 161_4kB 164_8kB 99_16kB 40_32kB 14_64kB 6_128kB 1_256kB 3_512kB 2_1024kB 1_2048kB 46*4096kB = 200788kB
3756 total pagecache pages
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
57344 pages of RAM
50323 free pages
1519 reserved pages
912 slab pages
3424 pages shared
0 pages swap cached
kobject: 'snd_bcm2835' (bf084b04): kobject_add_internal: parent: 'module', set: 'module'
kobject: 'holders' (cd97f9a0): kobject_add_internal: parent: 'snd_bcm2835', set: '<NULL>'
kobject: 'snd_bcm2835' (bf084b04): kobject_uevent_env
kobject: 'snd_bcm2835' (bf084b04): fill_kobj_path: path = '/module/snd_bcm2835'
kobject: 'bcm2835_AUD0' (cc933960): kobject_add_internal: parent: 'drivers', set: 'drivers'
snd_bcm2835_alsa_probe c03a6218 

Best,

John

**Comment by bootc** [comment]
Sadly your backtraces are useless as they don't include any function names, but your kobject debugging seems to point at the snd_bcm2835 driver. Do you have this compiled-in or as a module? This isn't a driver I've looked at before so I don't really have any idea about what might cause this.
